version: '3'
networks:
  todoapp-net:
services:
  pythonapp:
    image: volry/todoapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mate_root
      MYSQL_DATABASE: app_db
      MYSQL_USER: volry
      MYSQL_PASSWORD: mate_best
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
