# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=mate_root
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=volry
ENV MYSQL_PASSWORD=mate_best


# Expose port 3306 for MySQL connections
EXPOSE 3306

# Set the data directory as a volume
VOLUME /var/lib/mysql
